daemon: daemon.c
	gcc backup_dashboard.c check_file_uploads.c collect_reports.c daemon.c generate_reports.c lock_directories.c sig_handler.c unlock_directories.c update_timer.c -o daemon


clean:
	rm -f daemon